//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUSSIS.RawCode.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisburseReqItem
    {
        public int DisbursementId { get; set; }
        public int ReqId { get; set; }
        public int ItemId { get; set; }
        public int RetrieveQty { get; set; }
        public Nullable<int> DisburseQty { get; set; }
    
        public virtual Disbursement Disbursement { get; set; }
        public virtual Item Item { get; set; }
        public virtual Requisition Requisition { get; set; }
    }
}
