//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUSSIS.RawCode.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LUSSdb : DbContext
    {
        public LUSSdb()
            : base("name=LUSSdb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CollectionPoint> CollectionPoints { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Disbursement> Disbursements { get; set; }
        public virtual DbSet<DisburseReqItem> DisburseReqItems { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<InvAdjItem> InvAdjItems { get; set; }
        public virtual DbSet<InvAdjVoucher> InvAdjVouchers { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<PurchaseOrderItem> PurchaseOrderItems { get; set; }
        public virtual DbSet<Requisition> Requisitions { get; set; }
        public virtual DbSet<RequisitionItem> RequisitionItems { get; set; }
        public virtual DbSet<StoreEmployee> StoreEmployees { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
    }
}
