//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUSSIS.RawCode.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisitionReport
    {
        public int ItemId { get; set; }
        public string Item { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public int DeptID { get; set; }
        public string DeptName { get; set; }
        public System.DateTime SubmitDate { get; set; }
        public Nullable<int> Total_Requested { get; set; }
        public string SubmitMonth { get; set; }
    }
}
