//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUSSIS.RawCode.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransposedRequisitionReportByCost
    {
        public int ItemId { get; set; }
        public string SubmitMonth { get; set; }
        public System.DateTime SubmitDate { get; set; }
        public Nullable<decimal> C1 { get; set; }
        public Nullable<decimal> C2 { get; set; }
        public Nullable<decimal> C3 { get; set; }
        public Nullable<decimal> C4 { get; set; }
        public Nullable<decimal> C5 { get; set; }
        public Nullable<decimal> C6 { get; set; }
        public Nullable<decimal> C7 { get; set; }
        public Nullable<decimal> C8 { get; set; }
        public Nullable<decimal> C9 { get; set; }
        public Nullable<decimal> C10 { get; set; }
    }
}
