//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUSSIS.RawCode.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvAdjVoucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvAdjVoucher()
        {
            this.InvAdjItems = new HashSet<InvAdjItem>();
        }
    
        public int VoucherId { get; set; }
        public int RaiseBy { get; set; }
        public System.DateTime SubmitDate { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public Nullable<int> ApproveBy { get; set; }
        public string Status { get; set; }
        public string EmpComments { get; set; }
        public string ApproverComments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvAdjItem> InvAdjItems { get; set; }
        public virtual StoreEmployee StoreEmployee { get; set; }
        public virtual StoreEmployee StoreEmployee1 { get; set; }
    }
}
